package com.yourname.gramavasathi.util

import com.google.firebase.Timestamp
import com.yourname.gramavasathi.data.model.Listing
import java.util.Calendar

object MockData {
    private val pastDate = Calendar.getInstance().apply {
        set(2023, 0, 1)
    }.time

    val listings = listOf(
        Listing(
            id = "mock_1",
            title = "Nandi Hills Sunrise Farm",
            villageName = "Chikkaballapura",
            hostName = "Suresh Gowda",
            hostBio = "Third generation farmer offering authentic rural experiences.",
            description = "Wake up to stunning sunrise views over Nandi Hills. Experience cow milking, fresh farm breakfasts, and peaceful village life.",
            nearestLandmark = "3km from Nandi Hills",
            amenities = listOf("safe_water", "western_toilet", "food_included", "family_friendly"),
            activities = listOf("cow_milking", "birdwatching", "local_cooking"),
            readinessScore = 87,
            pricePerNight = 1200,
            avgRating = 4.8,
            reviewCount = 24,
            badges = listOf("verified_hygiene", "top_host", "family_friendly"),
            district = "Chikkaballapura",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_2",
            title = "Coorg Coffee Estate Stay",
            villageName = "Madikeri",
            hostName = "Kavitha Ponnappa",
            hostBio = "Coffee estate owner sharing the magic of Coorg with city guests.",
            description = "Stay amidst lush coffee plantations. Learn coffee picking, enjoy Coorgi cuisine, and trek through misty forests.",
            nearestLandmark = "5km from Raja Seat",
            amenities = listOf("safe_water", "western_toilet", "food_included"),
            activities = listOf("nature_walk", "local_cooking", "field_plowing"),
            readinessScore = 92,
            pricePerNight = 1800,
            avgRating = 4.9,
            reviewCount = 31,
            badges = listOf("verified_hygiene", "top_host"),
            district = "Kodagu",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1464226184884-fa280b87c399?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_3",
            title = "Mysuru Agri Homestay",
            villageName = "Srirangapatna",
            hostName = "Raju Naik",
            hostBio = "Farmer near the historic Srirangapatna island.",
            description = "Spend time on a working farm near the Kaveri river. Try field plowing, fishing, and enjoy traditional Mysuru cuisine.",
            nearestLandmark = "2km from Srirangapatna Fort",
            amenities = listOf("safe_water", "food_included"),
            activities = listOf("field_plowing", "cow_milking", "fishing"),
            readinessScore = 74,
            pricePerNight = 950,
            avgRating = 4.2,
            reviewCount = 11,
            badges = listOf("home_cooked_food"),
            district = "Mandya",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1595113316349-9fa4046419ed?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_4",
            title = "Chikmagalur Spice Farm",
            villageName = "Mudigere",
            hostName = "Anand Hegde",
            hostBio = "Spice and coffee farmer in the heart of Chikmagalur.",
            description = "Experience the aroma of cardamom and pepper on a working spice farm. Guided nature walks and home-cooked meals included.",
            nearestLandmark = "8km from Baba Budangiri",
            amenities = listOf("safe_water", "western_toilet", "food_included", "family_friendly"),
            activities = listOf("nature_walk", "local_cooking", "birdwatching"),
            readinessScore = 88,
            pricePerNight = 1500,
            avgRating = 4.7,
            reviewCount = 18,
            badges = listOf("verified_hygiene", "family_friendly"),
            district = "Chikmagalur",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_5",
            title = "Hassan Hoysala Farm Stay",
            villageName = "Belur",
            hostName = "Geetha Shetty",
            hostBio = "Homestay near the famous Hoysala temples.",
            description = "Stay near the UNESCO heritage Hoysala temples. Enjoy organic farming, sunrise temple visits, and traditional Karnataka meals.",
            nearestLandmark = "1km from Belur Temple",
            amenities = listOf("safe_water", "western_toilet", "family_friendly"),
            activities = listOf("field_plowing", "nature_walk", "local_cooking"),
            readinessScore = 81,
            pricePerNight = 1100,
            avgRating = 4.5,
            reviewCount = 14,
            badges = listOf("top_host", "family_friendly"),
            district = "Hassan",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1516467508483-a7212febe31a?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_6",
            title = "Hampi Rocky Farm",
            villageName = "Hospete",
            hostName = "Basavraj Kumar",
            hostBio = "Farmer near the ancient Vijayanagara ruins.",
            description = "A unique stay near the boulder-strewn landscape of Hampi. Sunrise views of ancient ruins, farming activities, and local food.",
            nearestLandmark = "4km from Virupaksha Temple",
            amenities = listOf("safe_water", "food_included"),
            activities = listOf("field_plowing", "cow_milking", "nature_walk"),
            readinessScore = 68,
            pricePerNight = 800,
            avgRating = 4.0,
            reviewCount = 8,
            badges = listOf("home_cooked_food"),
            district = "Vijayanagara",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_7",
            title = "Udupi Coastal Farm",
            villageName = "Manipal",
            hostName = "Shantha Bhat",
            hostBio = "Coconut farmer near the Arabian Sea coast.",
            description = "Experience coastal Karnataka life. Coconut harvesting, fresh seafood, and proximity to pristine beaches.",
            nearestLandmark = "6km from Malpe Beach",
            amenities = listOf("safe_water", "western_toilet", "food_included", "family_friendly"),
            activities = listOf("fishing", "local_cooking", "nature_walk", "birdwatching"),
            readinessScore = 90,
            pricePerNight = 1600,
            avgRating = 4.8,
            reviewCount = 22,
            badges = listOf("verified_hygiene", "top_host", "family_friendly"),
            district = "Udupi",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1560493676-04071c5f467b?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_8",
            title = "Dandeli Forest Stay",
            villageName = "Dandeli",
            hostName = "Mohan Naik",
            hostBio = "Forest-edge farmer and nature guide.",
            description = "Stay on the edge of Dandeli Wildlife Sanctuary. Bird spotting, river rafting nearby, and fresh forest produce.",
            nearestLandmark = "2km from Dadel Wildlife Sanctuary",
            amenities = listOf("safe_water", "family_friendly"),
            activities = listOf("birdwatching", "nature_walk", "fishing"),
            readinessScore = 72,
            pricePerNight = 1000,
            avgRating = 4.3,
            reviewCount = 9,
            badges = listOf("family_friendly"),
            district = "Uttara Kannada",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1444858291040-58f756a3bcd6?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_9",
            title = "Sakleshpura Tea Estate",
            villageName = "Sakleshpura",
            hostName = "Prema Rao",
            hostBio = "Tea estate owner in the misty Western Ghats.",
            description = "A serene stay amidst tea gardens in the Western Ghats. Tea picking experience, nature trails, and homemade food.",
            nearestLandmark = "3km from Manjarabad Fort",
            amenities = listOf("safe_water", "western_toilet", "food_included"),
            activities = listOf("field_plowing", "nature_walk", "local_cooking"),
            readinessScore = 83,
            pricePerNight = 1400,
            avgRating = 4.6,
            reviewCount = 16,
            badges = listOf("verified_hygiene", "home_cooked_food"),
            district = "Hassan",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        ),
        Listing(
            id = "mock_10",
            title = "Kodagu Riverside Home",
            villageName = "Virajpet",
            hostName = "Deva Cariappa",
            hostBio = "Coorgi family hosting guests since 2019.",
            description = "Riverside homestay in the heart of Kodagu. River bathing, paddy field walks, traditional Coorgi pork curry, and folk music.",
            nearestLandmark = "1km from Cauvery River",
            amenities = listOf("safe_water", "western_toilet", "food_included", "family_friendly"),
            activities = listOf("fishing", "field_plowing", "local_cooking", "folk_interaction"),
            readinessScore = 95,
            pricePerNight = 2000,
            avgRating = 5.0,
            reviewCount = 28,
            badges = listOf("verified_hygiene", "top_host", "family_friendly", "home_cooked_food"),
            district = "Kodagu",
            isPublished = true,
            imageUrls = listOf("https://images.unsplash.com/photo-1533062604082-2786d7946914?auto=format&fit=crop&w=800&q=80"),
            createdAt = Timestamp(pastDate)
        )
    )
}
